version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb-node
    environment:
      MONGO_INITDB_ROOT_USERNAME: sharenergy
      MONGO_INITDB_ROOT_PASSWORD: mongoDB2023desafio
      MONGO_INITDB_DATABASE: prod
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    container_name: nodeapp
    depends_on:
      - mongo
    build: 
      context: ./back-end
    volumes:
      - ./back-end:/api
      - /api/node_modules
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_CLUSTER=$DB_CLUSTER
      - JWT_KEY=$JWT_KEY
  app:
    container_name: reactapp
    build: 
      context: ./front-end
    volumes:
      - ./front-end:/app
      - /app/node_modules
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL
  # networks: 
  #     mongo-compose-network:
  #       driver: bridge