const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger.json";
// const endpointsFiles = ['./routes/places-routes.js', './routes/users-routes.js']
const endpointsFiles = ["./app.js"];

const doc = {
  info: {
    version: "1.0.1",
    title: "Sharenergy Project",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: "http",
  tags: [
    {
      name: "Login",
      description: "Endpoint of Login",
    },
    {
      name: "Clients",
      description: "Endpoint of Clients",
    },
  ],
  definitions: {
    Login: {
      username: "testjohn",
      password: "test12pass",
    },
    loginUser: {
      $username: "YOUR_USERNAME",
      $password: "YOUR_PASSWORD",
    },
    Clients: {
      name: "John Doe",
      email: "One of the most famous sky scrapers in the world!",
      phone: "1122224444",
      address: "20 W 34th St, New York, NY 10001, Estados Unidos",
      cpf: "11122233344",
    },
    getAllClients: [{ $ref: "#/definitions/Clients" }],
    createClient: {
      $name: "A complete name",
      $email: "email@email.com",
      $phone: "1122224444",
      $address: "20 W 34th St, New York, NY 10001, Estados Unidos",
      $cpf: "11122233344",
    },
    patchClient: {
      $name: "A complete new name",
      $email: "newemail@email.com",
      $phone: "3322224444",
      $address: "34th St, New York, NY 10001, Estados Unidos",
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc);
