const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger.json";
// const endpointsFiles = ['./routes/places-routes.js', './routes/users-routes.js']
const endpointsFiles = ["./app.js"];

const doc = {
  info: {
    version: "1.0.1",
    title: "ShareEnergy Project",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: "http",
  tags: [
    {
      name: "Users",
      description: "Endpoint of Users",
    },
    {
      name: "Clients",
      description: "Endpoint of Clients",
    },
  ],
  definitions: {
    Users: {
      name: "John Doe",
      email: "test@gmail.com",
      password: "test12pass"
    },
    Clients: {
      age: 28,
      email: "One of the most famous sky scrapers in the world!",
      name: "John Doe",
      username: "20 W 34th St, New York, NY 10001, Estados Unidos",
      image: "http://www.image.com/someimage.jpg",
    },
    loginUser: {
      $email: "YOUR_EMAIL@something.com",
      $password: "YOUR_PASSWORD",
    },
    signup: {
      $name: "Jhon Doe",
      $email: "YOUR_EMAIL@something.com",
      $password: "YOUR_PASSWORD",
    },
    getAllClients: [{ $ref: '#/definitions/Clients' }],
    createClient: {
      $age: 55,
      $email: "email@email.com",
      $name: "A complete name",
      $username: "Creator name",
      $image: "http://www.image.com/someimage.jpg"
    },
    putClient: {
      $age: 55,
      $email: "email@email.com",
      $name: "A complete name",
      $username: "Creator name",
      $image: "http://www.image.com/someimage.jpg"
    }
  },
  
};

swaggerAutogen(outputFile, endpointsFiles, doc);
