const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger.json";
// const endpointsFiles = ['./routes/places-routes.js', './routes/users-routes.js']
const endpointsFiles = ["./app.js"];

const doc = {
  info: {
    version: "1.0.1",
    title: "ShareEnergy Project",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: "http",
  tags: [
    {
      name: "Users",
      description: "Endpoint of Users",
    }
  ],
  definitions: {
    Users: {
      name: "John Doe",
      email: "test@gmail.com",
      password: "test12pass"
    },
    loginUser: {
      $email: "YOUR_EMAIL@something.com",
      $password: "YOUR_PASSWORD",
    },
    signup: {
      $name: "Jhon Doe",
      $email: "YOUR_EMAIL@something.com",
      $password: "YOUR_PASSWORD",
    },
    getAllUsers: [{ $ref: '#/definitions/Users' }],
  },
  
};

swaggerAutogen(outputFile, endpointsFiles, doc);
